
include:
  - rrd/compose-analytic.yaml
  - rest_api/compose.yaml
  - cyclomatic_complexity/compose-analytic.yaml

services:
  service_broker:
    build:
      context: ./
      dockerfile: ./service_broker/Dockerfile
    environment:
      CRON_REPO_UPDATE_SCHEDULE: 0 0 * * *
    volumes:
      - api.pmccabe_collector.restapi.org:/api

  vcs_project:
    build:
      context: ./
      dockerfile: ./observable_project_version_control/Dockerfile
    environment:
      - PROJECT_URL=${PROJECT_URL}
      - PROJECT_BRANCH=${PROJECT_BRANCH}
    volumes:
      - api.pmccabe_collector.project:/mnt
      - api.pmccabe_collector.restapi.org:/api

volumes:
  api.pmccabe_collector.project:
  api.pmccabe_collector.restapi.org:
    name: api.pmccabe_collector.restapi.org
    external: true
  api.pmccabe_collector.rrd_analytic:
    name: api.pmccabe_collector.rrd_analytic
    external: true
