include:
  - common/images/test_pseudo_fs/compose.yaml
  - cyclomatic_complexity/compose-analysis.integrational-test.yaml
  - rrd_analytic/compose-analysis.integrational-test.yaml
  - rest_api/compose-analysis.integrational-test.yaml
  #- common/compose-common.yaml
  - common/images/test_aggregator_image/compose.yaml

networks:
  api.pmccabe_collector.network:
    name: api.pmccabe_collector.network
    external: true

volumes:
  test_aggregator_logs_storage:
  api.pmccabe_collector.project:
  api.pmccabe_collector.restapi.org:
    name: api.pmccabe_collector.restapi.org
    external: true
  api.pmccabe_collector.rrd-analytic:
