
include:
  - submodules/compose.yaml
  - cyclomatic_complexity/compose.yaml
#  - observable_project_version_control/compose.yaml

services:
  vcs_project:
    build:
      context: ./
      dockerfile: ./observable_project_version_control/Dockerfile
    environment:
      - CRON_REPO_UPDATE_SCHEDULE="0 0 * * *"
      - PROJECT_URL=${PROJECT_URL}
      - PROJECT_BRANCH=${PROJECT_BRANCH}

    volumes:
      - api.pmccabe_collector.restapi.org:/api

volumes:
  api.pmccabe_collector.restapi.org:
    name: api.pmccabe_collector.restapi.org
    external: true
