include:
  - tests/compose-functional.test.yaml

services:
  file-uploader:
    build:
      context: ../..
      dockerfile: utility/file-uploader/Dockerfile
    environment:
      - MICROSERVICE_NAME=file-uploader
    volumes:
      - file-uploader-api-test:/api
      - file-uploads-test:/uploads
      - file-uploader-staging-test:/dev/shm/file-uploader

volumes:
  file-uploader-api-test:
  file-uploads-test:
  file-uploader-staging-test:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=256m,mode=0770
