include:
  - tests/compose-functional.test.yaml

services:
  http_proxy_service_a:
    build:
      context: ../../
      dockerfile: ./fs_api_proxy/http_proxy/Dockerfile
    environment:
        - UPSTREAM_SERVICE=mock_upstream_service
        - DOWNSTREAM_SERVICE=service_a
        - DOWNSTREAM_SERVICE_NETWORK_ADDR=stub_downstream_service_network_addr
    hostname: http_proxy_service_a
    networks:
      - api.pmccabe_collector.service.network
    volumes:
      - api.pmccabe_collector.restapi.org.fs_api_http_proxy.test:/api
#    ports:
#      - 6000:6000
#    depends_on:
#      - http_proxy_functional_api_initializer

  http_proxy_service_b:
    build:
      context: ../../
      dockerfile: ./fs_api_proxy/http_proxy/Dockerfile
    environment:
        - UPSTREAM_SERVICE=mock_upstream_service
        - DOWNSTREAM_SERVICE=service_b
        - DOWNSTREAM_SERVICE_NETWORK_ADDR=stub_downstream_service_network_addr
    hostname: http_proxy_service_b
    networks:
      - api.pmccabe_collector.service.network
    volumes:
      - api.pmccabe_collector.restapi.org.fs_api_http_proxy.test:/api

  http_proxy_service_unreachable_a:
    build:
      context: ../../
      dockerfile: ./fs_api_proxy/http_proxy/Dockerfile
    environment:
        - UPSTREAM_SERVICE=mock_upstream_service
        - DOWNSTREAM_SERVICE=service_unreachable_a
        - DOWNSTREAM_SERVICE_NETWORK_ADDR=stub_downstream_service_network_addr
        - DOWNSTREAM_SERVICE_CONNECT_ATTEMPT=-1
    hostname: http_proxy_service_unreachable_a
    networks:
      - api.pmccabe_collector.service.network
    volumes:
      - api.pmccabe_collector.restapi.org.fs_api_http_proxy.test:/api

networks:
  api.pmccabe_collector.service.network:
    name: api.pmccabe_collector.service.network
    external: false

volumes:
  api.pmccabe_collector.restapi.org.fs_api_http_proxy.test:
