include:
  - tests/compose-functional.test.yaml

services:
  http-proxy-service-a:
    build:
      context: ../../
      dockerfile: ./fs_api_proxy/http_proxy/Dockerfile
    environment:
        - UPSTREAM_SERVICE=mock-upstream-service
        - DOWNSTREAM_SERVICE=service_a
        - DOWNSTREAM_SERVICE_NETWORK_ADDR=stub-downstream-service-network-addr
    hostname: http-proxy-service-a
    networks:
      - api.pmccabe_collector.service.network
    volumes:
      - api.pmccabe_collector.restapi.org.fs-api-http-proxy.test:/api
#    ports:
#      - 6000:6000
#    depends_on:
#      - http_proxy_functional_api_initializer

  http-proxy-service-b:
    build:
      context: ../../
      dockerfile: ./fs_api_proxy/http_proxy/Dockerfile
    environment:
        - UPSTREAM_SERVICE=mock-upstream-service
        - DOWNSTREAM_SERVICE=service_b
        - DOWNSTREAM_SERVICE_NETWORK_ADDR=stub-downstream-service-network-addr
    hostname: http-proxy-service-b
    networks:
      - api.pmccabe_collector.service.network
    volumes:
      - api.pmccabe_collector.restapi.org.fs-api-http-proxy.test:/api

  http-proxy-service-unreachable-a:
    build:
      context: ../../
      dockerfile: ./fs_api_proxy/http_proxy/Dockerfile
    environment:
        - UPSTREAM_SERVICE=mock-upstream-service
        - DOWNSTREAM_SERVICE=service_unreachable_a
        - DOWNSTREAM_SERVICE_NETWORK_ADDR=stub-downstream-service-network-addr
        - DOWNSTREAM_SERVICE_CONNECT_ATTEMPT=-1
    hostname: http-proxy-service-unreachable-a
    networks:
      - api.pmccabe_collector.service.network
    volumes:
      - api.pmccabe_collector.restapi.org.fs-api-http-proxy.test:/api

networks:
  api.pmccabe_collector.service.network:
    name: api.pmccabe_collector.service.network
    external: false

volumes:
  api.pmccabe_collector.restapi.org.fs-api-http-proxy.test:
