services:
  rest_api:
    build:
      context: ../
      dockerfile: ./rest_api/Dockerfile
    environment:
      - FLASK_RUN_PORT=${FLASK_RUN_PORT:-5000}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST:-0.0.0.0}
    hostname: rest_api
    volumes:
      - api.pmccabe_collector.restapi.org:/api
    ports:
      - 5000:5000

volumes:
  api.pmccabe_collector.restapi.org:
    name: api.pmccabe_collector.restapi.org
    external: true
