include:
  - tests/compose-functional.test.yaml

services:
  rest_api:
    build:
      context: ../
      dockerfile: ./rest_api/Dockerfile
    hostname: rest_api
    volumes:
      - api.pmccabe_collector.restapi.org.rest_api.test:/api
    ports:
      - 5000:5000
    depends_on:
      - rest_api_functional_api_initializer

volumes:
  api.pmccabe_collector.restapi.org.rest_api.test:
