services:
  cc-visualizer:
    build:
      context: ../
      dockerfile: ./cyclomatic_complexity/Dockerfile
    depends_on:
      - syslog-ng
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:601"
        tag: "{{.Name}}"
    networks:
      - api.pmccabe_collector.network
    volumes:
      - api.pmccabe_collector.vcs-project:/mnt
      - api.pmccabe_collector.api.cc.http.private.org:/api

  cc-http-api:
    build:
      context: ../
      dockerfile: ./rest_api/Dockerfile
    depends_on:
      - syslog-ng
    environment:
      - FLASK_RUN_PORT=${FLASK_RUN_PORT:-5001}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST:-0.0.0.0}
      - WAIT_FOR_API_SERVICE_PROVIDER_INITIALIZED_ATTEMPTS=4
      - WAIT_FOR_API_SERVICE_PROVIDER_STARTED_ATTEMPTS=10
    hostname: cc-http-api
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:601"
        tag: "{{.Name}}"
    networks:
      - api.pmccabe_collector.network
    volumes:
      - api.pmccabe_collector.api.cc.http.private.org:/api
    ports:
      - 5001:5001

volumes:
  api.pmccabe_collector.vcs-project:
  api.pmccabe_collector.api.cc.http.private.org:
    name: api.pmccabe_collector.api.cc.http.private.org
    external: false
