services:
  cc_visualizer:
    build:
      context: ../
      dockerfile: ./cyclomatic_complexity/Dockerfile
    depends_on:
      - syslog-ng
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:601"
        tag: "{{.Name}}"
    networks:
      - api.pmccabe_collector.network
    volumes:
      - api.pmccabe_collector.project:/mnt
      - api.pmccabe_collector.restapi.org:/api

volumes:
  api.pmccabe_collector.project:
  api.pmccabe_collector.restapi.org:
    name: api.pmccabe_collector.restapi.org
    external: true
