services:
  cc_visualizer:
    build:
      context: ../
      dockerfile: ./cyclomatic_complexity/Dockerfile
    environment:
      - PROJECT_PATH=${PROJECT_PATH}
    volumes:
      - ${PROJECT_PATH}:/mnt
      - api.pmccabe_collector.restapi.org:/api

volumes:
  api.pmccabe_collector.restapi.org:
    name: api.pmccabe_collector.restapi.org
    external: true
