services:
  cc_visualizer:
    build:
      context: ../
      dockerfile: ./cyclomatic_complexity/Dockerfile
    volumes:
      - api.pmccabe_collector.project:/mnt
      - api.pmccabe_collector.restapi.org:/api

volumes:
  api.pmccabe_collector.project:
  api.pmccabe_collector.restapi.org:
    name: api.pmccabe_collector.restapi.org
    external: true
    #driver: local
    #driver_opts:
        #device: /tmp/docker,
        #o: bind,
        #type: none
