include:
  - tests/compose-analytic.http-api.integrational-test.yaml

services:
  http-integrational-test-http-proxy-cc:
    build:
      context: ../
      dockerfile: ./fs_api_proxy/http_proxy/Dockerfile
    environment:
        - UPSTREAM_SERVICE=cc-integrational-tester
        - DOWNSTREAM_SERVICE=cyclomatic_complexity
        - DOWNSTREAM_SERVICE_NETWORK_ADDR=cc-http-api:5001
        - DOWNSTREAM_SERVICE_CONNECT_ATTEMPT=${DOWNSTREAM_SERVICE_CONNECT_ATTEMPT:-900}
    networks:
      - api.pmccabe_collector.network
    volumes:
      - api.pmccabe_collector.restapi.cc.private.org:/api
      - api.pmccabe_collector.project.cc.private:/mnt

volumes:
  api.pmccabe_collector.restapi.cc.private.org:
    name: api.pmccabe_collector.restapi.cc.private.org
    external: false
  api.pmccabe_collector.project.cc.private:
    name: api.pmccabe_collector.project.cc.private
    external: false
