services:
  tap_subscriber:
    build:
      context: ../../../../
      dockerfile: common/images/streaming_test_aggregator/tap_subscriber/Dockerfile
    env_file:
      - ./.env
    environment:
      ENVOY_ADMIN_HOST: ${ENVOY_ADMIN_HOST:-envoy}
      ENVOY_ADMIN_PORT: ${ENVOY_ADMIN_PORT:-9901}
      ENVOY_TAP_CONFIG_ID: ${ENVOY_TAP_CONFIG_ID:-test_aggregator}
      WAIT_FOR_NEXT_TAP_BEFORE_FINISH_MSEC: ${WAIT_FOR_NEXT_TAP_BEFORE_FINISH_MSEC-15000}
      WAIT_FOR_FIRST_TAP_BEFORE_FINISH_MSEC: ${WAIT_FOR_FIRST_TAP_BEFORE_FINISH_MSEC-60000}
      MAX_WAIT_MSEC_UNTIL_FINISH: ${MAX_WAIT_MSEC_UNTIL_FINISH:-}
      MAX_BUFFERED_RX_BYTES: ${MAX_BUFFERED_RX_BYTES:-16777216}
      RETAIN_RAW_TAPS: ${RETAIN_RAW_TAPS:-false}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      KAFKA_DELIVERY_TIMEOUT_SECONDS: ${KAFKA_DELIVERY_TIMEOUT_SECONDS:-120}
      KAFKA_TOPIC: ${KAFKA_TOPIC:-test-capture-events}
      CAPTURE_ID: ${CAPTURE_ID:-functional-test}
    volumes:
      - tap_subscriber_logs:/logs

volumes:
  tap_subscriber_logs:
