services:
  rag-db:
    build:
      context: ../../
      dockerfile: ./ai_agents_framework/RAG/Dockerfile
    hostname: rag-db-host
    volumes:
      - api.pmccabe_collector.project.ai-agents-framework.rag.db:/mnt
    networks:
      - api.pmccabe_collector.network


networks:
  api.pmccabe_collector.network:
    name: api.pmccabe_collector.network
    external: false

volumes:
    api.pmccabe_collector.project.ai-agents-framework.rag.db:
