services:
  rest_api:
    build: ./
    environment:
      - FLASK_RUN_PORT=${FLASK_RUN_PORT:-5000}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST:-0.0.0.0}
    volumes:
      - main-shared-volume:/main_image_env
      - api.pmccabe_collector.restapi.org:/api
    ports:
      - 5000:5000

volumes:
  main-shared-volume:
  api.pmccabe_collector.restapi.org:
    name: api.pmccabe_collector.restapi.org
    external: true
