services:
  docs_dispatcher:
    build:
      context: ../../
      dockerfile: ./ai_agents_framework/docs_dispatcher/Dockerfile
    volumes:
      - api.pmccabe_collector.project.ai-agents-framework.docs-dispatcher.cfg:/etc/dispatcher
      - api.pmccabe_collector.restapi.org:/api

volumes:
  api.pmccabe_collector.restapi.org:
    name: api.pmccabe_collector.restapi.org
    external: true
  api.pmccabe_collector.project.ai-agents-framework.docs-dispatcher.cfg:
    name: api.pmccabe_collector.project.ai-agents-framework.docs-dispatcher.cfg
    external: true
