services:
  docs_dispatcher:
    build:
      context: ../../
      dockerfile: ./ai_agents_framework/docs_dispatcher/Dockerfile
    environment:
       BE_MYSQL_PASSWORD_FILE: /run/secrets/backend_mysql_db_password
       BE_MYSQL_LOGIN_FILE: /run/secrets/backend_mysql_db_login
       BE_MYSQL_MYSQL_DATABASE: rag_docs_database
    volumes:
      - api.pmccabe_collector.restapi.org:/api
    secrets:
       - backend_mysql_db_login
       - backend_mysql_db_password

volumes:
  api.pmccabe_collector.restapi.org:
    name: api.pmccabe_collector.restapi.org
    external: true

secrets:
   backend_mysql_db_login:
     file: sources/backend/mysql/default_user.txt
   backend_mysql_db_password:
     file: sources/backend/mysql/default_pwd.txt
