apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rrd-analytic-deployment
  labels:
    app: rrd_analytic_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rrd_analytic_app
  serviceName: rrd-analytic-service
  template:
    metadata:
      labels:
        app: rrd_analytic_app
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: rrd-analytic
        image: code-metric-platform-rrd-analytic
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /api
          name: api-pmccabecollector-api-rrd-http-private-org
          readOnly: false
        - mountPath: /rrd_data
          name: api-pmccabe-collector-rrd-analytic-storage
          readOnly: false
        ####
        # Mount ConfigMap params as files in FS, which are devoted to customize queries using pseudo FS API interface.
        # Unfortunately ConfigMap mounts as read-only volumes, which stops us from creating FS API node in those directory
        # due to lack of permissions on write: pipes cannot be created etc.
        ####
        # The only WA is to use `subPath`, which will mount a single file-parameter only, without touching access-right
        # of an entire FS API. In this case FS is not read-only and we still can leverage FS API advantages
        # "Query": "api.pmccabe_collector.restapi.org/rrd_analytic"
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/0.-mmcc
          subPath: 0.-mmcc
          name: cc-analytic-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/1.-tmcc
          subPath: 1.-tmcc
          name: cc-analytic-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/2.-sif
          subPath: 2.-sif
          name: cc-analytic-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/3.-lif
          subPath: 3.-lif
          name: cc-analytic-query-params
        # "Query": "api.pmccabe_collector.restapi.org/rrd_analytic/rrd"
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/00.--start
          subPath: 00.--start
          name: cc-rrd-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/01.--step
          subPath: 01.--step
          name: cc-rrd-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/02.NO_NAME_PARAM.0
          subPath: 02.NO_NAME_PARAM.0
          name: cc-rrd-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/03.NO_NAME_PARAM.1
          subPath: 03.NO_NAME_PARAM.1
          name: cc-rrd-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/04.NO_NAME_PARAM.2
          subPath: 04.NO_NAME_PARAM.2
          name: cc-rrd-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/05.NO_NAME_PARAM.3
          subPath: 05.NO_NAME_PARAM.3
          name: cc-rrd-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/06.NO_NAME_PARAM.4
          subPath: 06.NO_NAME_PARAM.4
          name: cc-rrd-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/07.NO_NAME_PARAM.5
          subPath: 07.NO_NAME_PARAM.5
          name: cc-rrd-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/08.NO_NAME_PARAM.6
          subPath: 08.NO_NAME_PARAM.6
          name: cc-rrd-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/09.NO_NAME_PARAM.7
          subPath: 09.NO_NAME_PARAM.7
          name: cc-rrd-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/10.NO_NAME_PARAM.8
          subPath: 10.NO_NAME_PARAM.8
          name: cc-rrd-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/11.NO_NAME_PARAM.9
          subPath: 11.NO_NAME_PARAM.9
          name: cc-rrd-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/12.NO_NAME_PARAM.10
          subPath: 12.NO_NAME_PARAM.10
          name: cc-rrd-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/13.NO_NAME_PARAM.11
          subPath: 13.NO_NAME_PARAM.11
          name: cc-rrd-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/14.NO_NAME_PARAM.12
          subPath: 14.NO_NAME_PARAM.12
          name: cc-rrd-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/15.--no-overwrite
          subPath: 15.--no-overwrite
          name: cc-rrd-query-params
        # "Query": "api.pmccabe_collector.restapi.org/rrd_analytic/rrd/collect"
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/collect/0.-method
          subPath: 0.-method
          name: cc-rrd-collect-query-params
        # "Query": "api.pmccabe_collector.restapi.org/rrd_analytic/rrd/select"
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/select/0.-path
          subPath: 0.-path
          name: cc-rrd-select-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/select/1.-name
          subPath: 1.-name
          name: cc-rrd-select-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/select/2.-type
          subPath: 2.-type
          name: cc-rrd-select-query-params
        # "Query": "api.pmccabe_collector.restapi.org/rrd_analytic/rrd/select/view"
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/select/view/0.-s
          subPath: 0.-s
          name: cc-rrd-view-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/select/view/1.-e
          subPath: 1.-e
          name: cc-rrd-view-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/select/view/2.NO_NAME_PARAM.0
          subPath: 2.NO_NAME_PARAM.0
          name: cc-rrd-view-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/select/view/3.package_counters
          subPath: 3.package_counters
          name: cc-rrd-view-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/select/view/4.leaf_counters
          subPath: 4.leaf_counters
          name: cc-rrd-view-query-params
        # "Query": "api.pmccabe_collector.restapi.org/rrd_analytic/rrd/select/plot_view"
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/select/plot_view/0.-a
          subPath: 0.-a
          name: cc-rrd-plot-view-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/select/plot_view/1.-x
          subPath: 1.-x
          name: cc-rrd-plot-view-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/select/plot_view/2.-s
          subPath: 2.-s
          name: cc-rrd-plot-view-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/select/plot_view/3.-e
          subPath: 3.-e
          name: cc-rrd-plot-view-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/select/plot_view/4.package_counters
          subPath: 4.package_counters
          name: cc-rrd-plot-view-query-params
        - mountPath: /api/api.pmccabe_collector.restapi.org/rrd_analytic/rrd/select/plot_view/5.leaf_counters
          subPath: 5.leaf_counters
          name: cc-rrd-plot-view-query-params
        securityContext:
          runAsUser: 1101
          runAsGroup: 23456
          capabilities:
            add:
            - NET_RAW
      - name: rrd-http-api
        image: code-metric-platform-rrd-http-api
        imagePullPolicy: Never
        env:
        - name: FLASK_RUN_PORT
          value: "5002"
        - name: WAIT_FOR_API_SERVICE_PROVIDER_INITIALIZED_ATTEMPTS
          value: "4"
        - name: WAIT_FOR_API_SERVICE_PROVIDER_STARTED_ATTEMPTS
          value: "90"
        volumeMounts:
        - mountPath: /api
          name: api-pmccabecollector-api-rrd-http-private-org
        ports:
        - containerPort: 5002
        securityContext:
          runAsUser: 1201
          runAsGroup: 23456
          capabilities:
            add:
            - NET_RAW
      - name: rrd-http-proxy-cc
        image: code-metric-platform-rrd-http-proxy-cc
        imagePullPolicy: Never
        env:
        - name: UPSTREAM_SERVICE
          value: rrd_analytic
        - name: DOWNSTREAM_SERVICE
          value: cyclomatic_complexity
        - name: DOWNSTREAM_SERVICE_NETWORK_ADDR
          value: cc-visualizer-service:5001
        - name: DOWNSTREAM_SERVICE_CONNECT_ATTEMPT
          value: "900"
        securityContext:
          runAsUser: 2001
          runAsGroup: 23456
          capabilities:
            add:
            - NET_RAW
        volumeMounts:
        - mountPath: /api
          name: api-pmccabecollector-api-rrd-http-private-org
      volumes:
      - name: api-pmccabe-collector-rrd-analytic-storage
        persistentVolumeClaim:
          claimName: rrd-analytic-storage
      - name: api-pmccabecollector-api-rrd-http-private-org
        emptyDir:
            sizeLimit: 500Mi
        # Query params customization leveraging k8s ConfigMap
      - name: cc-analytic-query-params
        configMap:
           name: cc-analytic-cm
           defaultMode: 0777
      - name: cc-rrd-query-params
        configMap:
           name: cc-rrd-cm
           defaultMode: 0777
      - name: cc-rrd-collect-query-params
        configMap:
           name: cc-rrd-collect-cm
           defaultMode: 0777
      - name: cc-rrd-select-query-params
        configMap:
           name: cc-rrd-select-cm
           defaultMode: 0777
      - name: cc-rrd-view-query-params
        configMap:
           name: cc-rrd-view-cm
           defaultMode: 0777
      - name: cc-rrd-plot-view-query-params
        configMap:
           name: cc-rrd-plot-view-cm
           defaultMode: 0777
  volumeClaimTemplates:
  - metadata:
      name: api-pmccabe-collector-rrd-analytic-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 1Gi
