services:
  rrd_analytic:
    build:
      context: ../
      dockerfile: ./rrd/local/Dockerfile
    volumes:
      - api.pmccabe_collector.restapi.org:/api

volumes:
  api.pmccabe_collector.restapi.org:
    name: api.pmccabe_collector.restapi.org
    external: true
