include:
  - tests/compose-functional.test.yaml

services:
  rrd_analytic:
    build:
      context: ../
      dockerfile: ./rrd/Dockerfile
    #container_name: rrd_analytic_functional
    hostname: rrd_analytic_functional
    volumes:
      - api.pmccabe_collector.project.rrd.test:/mnt
      - api.pmccabe_collector.restapi.org.rrd.test:/api
      - api.pmccabe_collector.rrd.rrd_analytic:/rrd_data

volumes:
  api.pmccabe_collector.project.rrd.test:
  api.pmccabe_collector.restapi.org.rrd.test:
  api.pmccabe_collector.rrd.rrd_analytic:
