services:
  rag:
    logging: &streaming-logging
      driver: syslog
      options: { syslog-address: "tcp://localhost:13601", tag: "{{.Name}}" }
  rag-functional-tester:
    logging: *streaming-logging
