services:
  rag:
    logging: &streaming-logging
      driver: syslog
      options: { syslog-address: "tcp://localhost:13601", tag: "{{.Name}}" }

networks:
  api.pmccabe_collector.network:
    name: api.pmccabe_collector.network
    external: true
