name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Build the VCS Docker image
      run: docker build -f observable_project_version_control/Dockerfile -t vcs_project:$DATE .
      env:
        DATE: ${{ steps.date.outputs.date }}
    - name: Build the CC Docker image
      run: docker build cyclomatic_complexity --tag cc_visualizer:$DATE
      env:
        DATE: ${{ steps.date.outputs.date }}
    - name: Build the RRD Docker image
      run: docker build submodules/rrd/local --tag rrd_analytic:$DATE
      env:
        DATE: ${{ steps.date.outputs.date }}
    - name: Build the REST API Docker image
      run: docker build submodules/rest_api --tag rest_api:$DATE
      env:
        DATE: ${{ steps.date.outputs.date }}
    - name: Build the Service Broker Docker image
      run: docker build -f service_broker/Dockerfile -t broker:$DATE .
      env:
        DATE: ${{ steps.date.outputs.date }}
    - name: Create API volume
      run: mkdir -p api && chmod 777 api && docker volume create -d local -o type=none -o device=api -o o=bind api.pmccabe_collector.restapi.org
    - name: Run VCS Docker
      run: docker run -i --name vcs_project -v "api:/api" -e PROJECT_URL=https://github.com/SergeyIvanov87/TrafficInspector.git -e PROJECT_BRANCH=master vcs_project:$DATE
      env:
        DATE: ${{ steps.date.outputs.date }}
    - name: Run CC Docker
      run: docker run -i --name cc_visualizer -v api.pmccabe_collector.restapi.org:/api --volumes-from vcs_project cc_visualizer:$DATE
      env:
        DATE: ${{ steps.date.outputs.date }}
    - name: Create RRD volume
      run: mkdir -p rrd_data && chmod 777 rrd_data && docker volume create -d local -o type=none -o device=rrd_data -o o=bind api.pmccabe_collector.rrd_analytic
    - name: Run RRD Docker
      run: docker run -i --name rrd_analytic -v api.pmccabe_collector.restapi.org:/api -v api.pmccabe_collector.rrd_analytic:/rrd_data --volumes-from cc_visualizer rrd_analytic:$DATE
      env:
        DATE: ${{ steps.date.outputs.date }}
    - name: Run REST Docker
      run: docker run -i --name rest_api -v api.pmccabe_collector.restapi.org:/api -e FLASK_RUN_PORT=5000 -e FLASK_RUN_HOST=0.0.0.0 --volumes-from cc_visualizer -p 5000:5000 rest_api:$DATE
      env:
        DATE: ${{ steps.date.outputs.date }}
    - name: Run Broker Docker
      run: docker run -i --name broker --volumes-from vcs_project -e CRON_REPO_UPDATE_SCHEDULE="0 0 * * *" service_broker:$DATE
      env:
        DATE: ${{ steps.date.outputs.date }}

