name: Minikube CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# See https://github.com/marketplace/actions/setup-minikube
jobs:
  minikube_setup_job:
    runs-on: ubuntu-latest
    name: minikube_setup_job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: start minikube
        uses: medyagh/setup-minikube@latest
        with:
          cache: false
          minikube-version: 1.24.0
#          driver: kvm2
#          container-runtime: containerd
          kubernetes-version: v1.22.3
          nodes: 2
          cpus: 4
          memory: 4000m
          cni: bridge
#          addons: registry,ingress
          extra-config: 'kubelet.max-pods=10'
          feature-gates: 'DownwardAPIHugePages=true'
          mount-path: '/Users/user1/test-files:/testdata'
          wait: false
          insecure-registry: 'localhost:5000,10.0.0.0/24'
          #start-args: '--delete-on-failure --subnet 192.168.50.0'
          start-args: '--delete-on-failure'
      - name: kubectl
        run: kubectl get pods -A
      - name: Activate docker env
        run: eval $(minikube docker-env)
      - name: Build Docker images locally
        run: docker compose -f compose-analytic-http-api.yaml build
      - name: Deploy CC
        run: kubectl apply -f k8s/deployment/cc_visualizer-http.yaml
      - name: Deploy CC Service
        run: kubectl apply -f k8s/service/cc_visualizer-http.yaml
      - name: Check CC service health
        run: sleep 30 && curl  --head --fail "`minikube ip`:30001//api.pmccabe_collector.restapi.org"
