name: Minikube CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# See https://github.com/marketplace/actions/setup-minikube
jobs:
  minikube_setup_job:
    runs-on: ubuntu-latest
    name: minikube_setup_job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: start minikube
        uses: medyagh/setup-minikube@latest
      - name: kubectl
        run: kubectl get pods -A
      - name: Activate docker env & Build Docker images locally
        run: eval $(minikube docker-env) && docker --version && DOCKER_BUILDKIT=0 docker compose -f compose-analytic-http-api.yaml build
      - name: Deploy CC
        run: kubectl apply -f k8s/configMap/cc_visualizer-http.yaml && kubectl apply -f k8s/deployment/cc_visualizer-http.yaml
      - name: Deploy CC Service
        run: kubectl apply -f k8s/service/cc_visualizer-http.yaml
      - name: Check PODs and SVC
        run: kubectl get cm && kubectl describe pods && kubectl describe svc
      - name: Check CC service health
        run: sleep 90 && curl  --head --fail "`minikube ip`:30001//api.pmccabe_collector.restapi.org"
